# Generated by Django 4.0.3 on 2022-07-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0006_rename_conuntry_customuser_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='country',
            new_name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
