# Generated by Django 4.0.3 on 2022-07-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0007_rename_country_customuser_location_customuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='location',
            new_name='area',
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='governorate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
