# Generated by Django 4.0.3 on 2022-04-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsys', '0002_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=100)),
            ],
        ),
    ]
