# Generated by Django 4.0.3 on 2022-04-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0005_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='conuntry',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
