# Generated by Django 4.0.3 on 2022-04-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('describe', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events_imgs')),
            ],
        ),
    ]
